inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'

Rails:
  Enabled: true

# Rails
Rails/HttpPositionalArguments:
  Enabled: false

# Metrics
Metrics/LineLength:
  Max: 100

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
